[general]
#output = "icarus_bnb_ccpi0_cvext"
#output = "icarus_bnb_ccpi0_cv_vars"
#output = "icarus_bnb_ccpi0_onbeam_offbeam"
output = "icarus_bnb_ccpi0_dev"

[[sample]]
name = "cvext"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/cvext/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "cv"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input*.flat.root"
ismc = true
disable = false

[[sample]]
name = "onbeam"
path = "/pnfs/icarus/persistent/users/mueller/production/data/onbeam/input*.flat.root"
ismc = false
disable = true

[[sample]]
name = "offbeam"
path = "/pnfs/icarus/persistent/users/mueller/production/data/offbeam/input*.flat.root"
ismc = false
disable = true

[[sample]]
name = "var00"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var00/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var01"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var01/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var02"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var02/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var03m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var03m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var03p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var03p/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var04"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var04/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var05"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var05/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var06"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var06/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var07"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var07/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var08"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var08/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var09m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var09m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var09p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var09p/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var10m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var10m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var10p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var10p/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var11"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var11/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var12m"
path = "/pnfs/icarus/scratch/users/mueller/production/simulation/var12m/flat/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var12p"
path = "/pnfs/icarus/scratch/users/mueller/production/simulation/var12p/flat/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var13m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var13m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var13p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var13p/input*.flat.root"
ismc = true
disable = true

[[tree]]
name = "selected_nu"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut", type = "reco"},
    {name = "flash_cut", type = "reco", parameters = [-0.5, 1.6]},
    {name = "base_topology_cut", type = "reco"},
    {name = "leading_shower_energy_cut", type = "reco"},
    {name = "valid_pi0_mass_cut", type = "reco"},
    {name = "neutrino", type = "true"},
    {name = "trigger_emulation_cut",     type = "event", decrements_exposure = false },
    {name = "data_quality_cut",          type = "event", decrements_exposure = true },
    {name = "beam_quality_cut",          type = "spill", decrements_exposure = false }, # Should decrement exposure, but CAF files are bugged
    {name = "bnb_fom2_cut",              type = "event", decrements_exposure = false, parameters = [0.98,]}, # Should decrement exposure, but CAF files are bugged
]
branch = [

    # True interaction info
    {name = "neutrino_id", type = "true"},
    {name = "pdg", type = "mctruth"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category_topology_v1", type = "true"},
    {name = "category_topology_v2", type = "true"},
    {name = "category_topology_v3", type = "true"},
    {name = "category_topology_v4", type = "true"},

    # Interaction observables
    {name = "flash_time", type = "reco"},
    {name = "visible_energy", type = "both"},
    {name = "Q2", type = "both"},
    {name = "W", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dpL", type = "both"},
    {name = "pn", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "vertex_x", type = "both"},
    {name = "vertex_y", type = "both"},
    {name = "vertex_z", type = "both"},

    # Muon observables
    {name = "muon_momentum_mag", type = "both"},
    {name = "muon_beam_costheta", type = "both"},

    # Neutral pion observables
    {name = "pi0_momentum_mag", type = "both"},
    {name = "pi0_beam_costheta", type = "both"},
    {name = "pi0_mass", type = "both"},
    {name = "pi0_photons_costheta", type = "both"},
    {name = "pi0_leading_photon_energy", type = "both"},
    {name = "pi0_leading_photon_conv_dist", type = "both"},
    {name = "pi0_subleading_photon_energy", type = "both"},
    {name = "pi0_subleading_photon_conv_dist", type = "both"},

    # GUNDAM
    {name = "is_nu", type = "reco"},
    {name = "is_data", type = "reco"},
    {name = "cut_type", type = "reco"}
]

[[tree]]
name = "selected_cos"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut", type = "reco"},
    {name = "flash_cut", type = "reco", parameters = [-0.5, 1.6]},
    {name = "base_topology_cut", type = "reco"},
    {name = "leading_shower_energy_cut", type = "reco"},
    {name = "valid_pi0_mass_cut", type = "reco"},
    {name = "cosmic", type = "true"},
    {name = "trigger_emulation_cut",     type = "event", decrements_exposure = false },
    {name = "data_quality_cut",          type = "event", decrements_exposure = true },
    {name = "beam_quality_cut",          type = "spill", decrements_exposure = false }, # Should decrement exposure, but CAF files are bugged
    {name = "bnb_fom2_cut",              type = "event", decrements_exposure = false, parameters = [0.98,]}, # Should decrement exposure, but CAF files are bugged
]
branch = [

    # True interaction info
    {name = "neutrino_id", type = "true"},
    {name = "pdg", type = "mctruth"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category_topology_v1", type = "true"},
    {name = "category_topology_v2", type = "true"},
    {name = "category_topology_v3", type = "true"},
    {name = "category_topology_v4", type = "true"},

    # Interaction observables
    {name = "flash_time", type = "reco"},
    {name = "visible_energy", type = "both"},
    {name = "Q2", type = "both"},
    {name = "W", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dpL", type = "both"},
    {name = "pn", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "vertex_x", type = "both"},
    {name = "vertex_y", type = "both"},
    {name = "vertex_z", type = "both"},

    # Muon observables
    {name = "muon_momentum_mag", type = "both"},
    {name = "muon_beam_costheta", type = "both"},

    # Neutral pion observables
    {name = "pi0_momentum_mag", type = "both"},
    {name = "pi0_beam_costheta", type = "both"},
    {name = "pi0_mass", type = "both"},
    {name = "pi0_photons_costheta", type = "both"},
    {name = "pi0_leading_photon_energy", type = "both"},
    {name = "pi0_leading_photon_conv_dist", type = "both"},
    {name = "pi0_subleading_photon_energy", type = "both"},
    {name = "pi0_subleading_photon_conv_dist", type = "both"},

    # GUNDAM
    {name = "is_nu", type = "reco"},
    {name = "is_data", type = "reco"},
    {name = "cut_type", type = "reco"}
]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    {name = "neutrino", type = "true"},
    {name = "fiducial_cut", type = "true"},
    {name = "cc1mu", type = "true"},
    {name = "zero_pi", type = "true"},
    {name = "one_pi0", type = "true"},
    {name = "trigger_emulation_cut", type = "event", decrements_exposure = false },
]
branch = [

    # True interaction info
    {name = "neutrino_id", type = "true"},
    {name = "pdg", type = "mctruth"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category_topology_v1", type = "true"},
    {name = "category_topology_v2", type = "true"},
    {name = "category_topology_v3", type = "true"},
    {name = "category_topology_v4", type = "true"},

    # Interaction observables
    {name = "visible_energy", type = "both"},
    {name = "Q2", type = "both"},
    {name = "W", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dpL", type = "both"},
    {name = "pn", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "vertex_x", type = "both"},
    {name = "vertex_y", type = "both"},
    {name = "vertex_z", type = "both"},

    # Muon observables
    {name = "muon_momentum_mag", type = "both"},
    {name = "muon_beam_costheta", type = "both"},

    # Neutral pion observables
    {name = "pi0_momentum_mag", type = "both"},
    {name = "pi0_beam_costheta", type = "both"},
    {name = "pi0_mass", type = "both"},
    {name = "pi0_photons_costheta", type = "both"},
    {name = "pi0_leading_photon_energy", type = "both"},
    {name = "pi0_leading_photon_conv_dist", type = "both"},
    {name = "pi0_subleading_photon_energy", type = "both"},
    {name = "pi0_subleading_photon_conv_dist", type = "both"},

    # GUNDAM
    {name = "is_nu", type = "reco"},
    {name = "is_data", type = "reco"},
    {name = "cut_type", type = "reco"},

    # Cuts for efficiency analysis
    {name = "flash_icarus_satisfied", type = "reco"},
    {name = "fiducial_satisfied", type = "reco"},
    {name = "base_topology_satisfied", type = "reco"},
    {name = "leading_shower_energy_satisfied", type = "reco"},
    {name = "valid_pi0_mass_satisfied", type = "reco"}
    #{name = "trigger_emulation_satisfied", type = "event"}
]
