[general]
output = "icarus_bnb_energy_calib"

[[sample]]
name = "cv"
path = "/pnfs/icarus/persistent/users/mueller/mixed/simulation/nominal/input*.flat.root"
ismc = true
disable = false

[[tree]]
name = "muon"
sim_only = true
mode = "true"
cut = [
    {name = "in_time", type = "true_particle", parameters=[0, 1.6]},
    {name = "is_pid", type = "true_particle", parameters=[2]},
    {name = "is_primary", type = "true_particle"},
    {name = "containment_cut", type = "true_particle"}
]
branch = [
    {name = "ke", type = "both_particle"},
    {name = "csda_ke", type = "both_particle"},
    {name = "mcs_ke", type = "both_particle"},
    {name = "calo_ke", type = "both_particle"},
    {name = "primary_classification", type = "both_particle"},
    {name = "pid", type = "both_particle"},
    {name = "containment", type = "both_particle"}
]

[[tree]]
name = "photon"
sim_only = true
mode = "true"
cut = [
    {name = "in_time", type = "true_particle", parameters=[0, 1.6]},
    {name = "is_pid", type = "true_particle", parameters=[0]},
    {name = "is_primary", type = "true_particle"},
    {name = "containment_cut", type = "true_particle"}
]
branch = [
       {name = "ke", type = "both_particle"},
       {name = "calo_ke", type = "both_particle"},
       {name = "calo_ke_adj", type = "both_particle", parameters = [0.8091]},
       {name = "primary_classification", type = "both_particle"},
       {name = "pid", type = "both_particle"},
       {name = "containment", type = "both_particle"}
]