[general]
output = "michel"
pidfn = "default_pid"
primfn = "default_primary_classification"

[[sample]]
name = "simulation"
path = "/pnfs/sbnd/scratch/users/mueller/production02272026/batch0/0000/*/sys/merged-caf-jobid*.flat.root"
ismc = true
disable = false

[[sample]]
name = "offbeam"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/offbeamlight/*.flat.root"
ismc = false
disable = true

[[tree]]
name = "michel"
sim_only = false
mode = "reco"
cut = [
#   {name = "is_not_cathodecrosser", type = "reco"},
    {name = "single_michel",         type = "reco",  parameters = [15,] },
    {name = "michel_attached_muon",  type = "reco",  parameters = [15, 0, 10,] },
    {name = "containment_cut",       type = "reco_particle"},
    {name = "is_semantic_type",      type = "reco_particle", parameters = [2,]},
]
branch = [
    {name = "nu_id",                 type = "true_particle"},
    {name = "semantic_type",         type = "true_particle"},
    {name = "containment",           type = "true_particle"},
    {name = "pdg",                   type = "true_particle"},
    {name = "ke",                    type = "both_particle"},
    {name = "calo_ke",               type = "reco_particle"},
]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
#   {name = "is_not_cathodecrosser", type = "true"},
    {name = "single_michel",         type = "true",  parameters = [15,] },
    {name = "containment_cut",       type = "true_particle"},
    {name = "is_semantic_type",      type = "true_particle", parameters = [2,]},
]
branch = [
    {name = "containment_cut",       type = "reco_particle"},
    {name = "is_semantic_type",      type = "reco_particle", parameters = [2,]},
    {name = "ke",                    type = "both_particle"},
]