[general]
output = "icarus_ncpi0_offbeam_csugrant"

[[sample]]
name = "cv"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "onbeam"
path = "/pnfs/icarus/persistent/users/mueller/production/data/onbeam/input*.flat.root"
ismc = false
disable = true

[[sample]]
name = "offbeam"
path = "/pnfs/icarus/persistent/users/mueller/production/data/offbeam/input*.flat.root"
ismc = false
disable = false

[[tree]]
name = "selected_nu"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut", type = "reco"},
    {name = "flash_cut", type = "reco", parameters = [-0.5, 1.6]},
    {name = "base_topology_cut", type = "reco"},
    {name = "num_protons_cut", type = "reco", parameters = [-1, 0]},
    {name = "leading_shower_energy_cut", type = "reco"},
    {name = "valid_pi0_mass_cut", type = "reco"},
    {name = "neutrino", type = "true"},
    {name = "trigger_emulation_cut",     type = "event", decrements_exposure = false },
    {name = "data_quality_cut",          type = "event", decrements_exposure = true },
    #{name = "beam_quality_cut",          type = "spill", decrements_exposure = false }, # Should decrement exposure, but CAF files are bugged
    #{name = "bnb_fom2_cut",              type = "event", decrements_exposure = false, parameters = [0.98,]}, # Should decrement exposure, but CAF files are bugged
]
branch = [

    # True interaction info
    {name = "neutrino_id", type = "true"},
    {name = "pdg", type = "mctruth"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category_topology_v2", type = "true", parameters = [-1, 0]},    

    # Interaction observables
    {name = "flash_time", type = "reco"},
    {name = "visible_energy", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "vertex_x", type = "both"},
    {name = "vertex_y", type = "both"},
    {name = "vertex_z", type = "both"},

    # Neutral pion observables
    {name = "pi0_momentum_mag", type = "both"},
    {name = "pi0_beam_costheta", type = "both"},
    {name = "pi0_mass", type = "both"},
    {name = "pi0_photons_costheta", type = "both"},
    {name = "pi0_leading_photon_energy", type = "both"},
    {name = "pi0_leading_photon_conv_dist", type = "both"},
    {name = "pi0_subleading_photon_energy", type = "both"},
    {name = "pi0_subleading_photon_conv_dist", type = "both"},

    # Proton observables
    {name = "num_primary_protons", type = "both"},
    {name = "num_primary_protons_thresh", type = "both"},

    # GUNDAM
    {name = "is_nu", type = "reco"},
    {name = "is_data", type = "reco"},
    {name = "cut_type", type = "reco"}
]

[[tree]]
name = "selected_cos"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut", type = "reco"},
    {name = "flash_cut", type = "reco", parameters = [-0.5, 1.6]},
    {name = "base_topology_cut", type = "reco"},
    {name = "num_protons_cut", type = "reco", parameters = [-1, 0]},
    {name = "leading_shower_energy_cut", type = "reco"},
    {name = "valid_pi0_mass_cut", type = "reco"},
    {name = "cosmic", type = "true"},
    {name = "trigger_emulation_cut",     type = "event", decrements_exposure = false },
    {name = "data_quality_cut",          type = "event", decrements_exposure = true },
    #{name = "beam_quality_cut",          type = "spill", decrements_exposure = false }, # Should decrement exposure, but CAF files are bugged
    #{name = "bnb_fom2_cut",              type = "event", decrements_exposure = false, parameters = [0.98,]}, # Should decrement exposure, but CAF files are bugged
]
branch = [

    # True interaction info
    {name = "neutrino_id", type = "true"},
    {name = "pdg", type = "mctruth"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category_topology_v2", type = "true", parameters = [-1, 0]},

    # Interaction observables
    {name = "flash_time", type = "reco"},
    {name = "visible_energy", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "vertex_x", type = "both"},
    {name = "vertex_y", type = "both"},
    {name = "vertex_z", type = "both"},

    # Neutral pion observables
    {name = "pi0_momentum_mag", type = "both"},
    {name = "pi0_beam_costheta", type = "both"},
    {name = "pi0_mass", type = "both"},
    {name = "pi0_photons_costheta", type = "both"},
    {name = "pi0_leading_photon_energy", type = "both"},
    {name = "pi0_leading_photon_conv_dist", type = "both"},
    {name = "pi0_subleading_photon_energy", type = "both"},
    {name = "pi0_subleading_photon_conv_dist", type = "both"},

    # Proton observables
    {name = "num_primary_protons", type = "both"},
    {name = "num_primary_protons_thresh", type = "both"}, 

    # GUNDAM
    {name = "is_nu", type = "reco"},
    {name = "is_data", type = "reco"},
    {name = "cut_type", type = "reco"}
]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    {name = "neutrino", type = "true"},
    {name = "fiducial_cut", type = "true"},
    {name = "nc0mu", type = "true"},
    {name = "zero_pi", type = "true"},
    {name = "one_pi0", type = "true"},
    {name = "num_protons_cut", type = "true", parameters = [-1, 0]},
]
branch = [

    # True interaction info
    {name = "neutrino_id", type = "true"},
    {name = "pdg", type = "mctruth"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category_topology_v2", type = "true", parameters = [-1, 0]},

    # Interaction observables
    {name = "visible_energy", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "vertex_x", type = "both"},
    {name = "vertex_y", type = "both"},
    {name = "vertex_z", type = "both"},

    # Neutral pion observables
    {name = "pi0_momentum_mag", type = "both"},
    {name = "pi0_beam_costheta", type = "both"},
    {name = "pi0_mass", type = "both"},
    {name = "pi0_photons_costheta", type = "both"},
    {name = "pi0_leading_photon_energy", type = "both"},
    {name = "pi0_leading_photon_conv_dist", type = "both"},
    {name = "pi0_subleading_photon_energy", type = "both"},
    {name = "pi0_subleading_photon_conv_dist", type = "both"},

    # Proton observables
    {name = "num_primary_protons", type = "both"},
    {name = "num_primary_protons_thresh", type = "both"},

    # GUNDAM
    {name = "is_nu", type = "reco"},
    {name = "is_data", type = "reco"},
    {name = "cut_type", type = "reco"},

    # Cuts for efficiency analysis
    {name = "fiducial_cut", type = "both"},
    {name = "flash_cut", type = "reco", parameters = [-0.5, 1.6]},
    {name = "base_topology_cut", type = "reco"},
    {name = "leading_shower_energy_cut", type = "reco"},
    {name = "valid_pi0_mass_cut", type = "reco"},
    #{name = "trigger_emulation_cut", type = "event", decrements_exposure = false},


]
