[general]
output = "shower_260116"
primfn = "default_primary_classification"
pidfn = "default_pid"
calofn = "default_calo_ke"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]
recopi0thresh = [
    "@photon_threshold",
    "@leading_photon_threshold",
]

[parameters]
photon_threshold = 25.0
electron_threshold = 200.0
shower_threshold = 200.0
muon_threshold = 50.0
pion_threshold = 25.0
proton_threshold = 50.0
pi0_threshold = 0.0

leading_photon_threshold = 40.0
pi0_mass_veto_low = 0.0
pi0_mass_veto_high = 400.0
flash_low_t = -0.5
flash_high_t = 1.6
bnb_fom2_cut = 0.98

[[sample]]
name = "offbeam"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/offbeamlight/*.flat.root"
ismc = false

[[sample]]
name = "onbeam"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/devsample/*.flat.root"
ismc = false

[[sample]]
name = "simulation"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"
ismc = true

[[tree]]
name = "selected"
sim_only = false
add_systematics = true
mode = "reco"
cut = [
    { name = "fiducial_cut",         type = "reco" }, 
    { name = "valid_flashmatch",     type = "reco" },
    { name = "!no_showers",          type = "reco", parameters = [ "@shower_threshold" ] }
]
branch = [
    { name = "neutrino_id",           type = "true"    },
    { name = "cc",                    type = "mctruth" },
    { name = "pdg",                   type = "mctruth" },
    { name = "parent_pdg",            type = "mctruth" },
    { name = "interaction_type",      type = "mctruth" },
    { name = "neutrino_energy",       type = "mctruth" },
    { name = "visible_energy",        type = "both"    },
    { name = "fiducial",              type = "reco"    },
    { name = "containment",           type = "reco"    },
    { name = "photon_multiplicity",   type = "both", parameters = [ "@photon_threshold"    ]},
    { name = "electron_multiplicity", type = "both", parameters = [ "@electron_threshold"  ]},
    { name = "muon_multiplicity",     type = "both", parameters = [ "@muon_threshold"      ]},
    { name = "pion_multiplicity",     type = "both", parameters = [ "@pion_threshold"      ]},
    { name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold"    ]},
    { name = "ke",                    type = "both_particle", selector = "leading_shower"   },
    { name = "start_dedx",            type = "reco_particle", selector = "leading_shower"   },
    { name = "start_straightness",    type = "reco_particle", selector = "leading_shower"   },
    { name = "axial_spread",          type = "reco_particle", selector = "leading_shower"   },
    { name = "directional_spread",    type = "reco_particle", selector = "leading_shower"   },
    { name = "vertex_distance",       type = "reco_particle", selector = "leading_shower"   },
    { name = "photon_softmax",        type = "reco_particle", selector = "leading_shower"   },
    { name = "electron_softmax",      type = "reco_particle", selector = "leading_shower"   },
    { name = "primary_softmax",       type = "reco_particle", selector = "leading_shower"   },
    { name = "semantic_type",         type = "both_particle", selector = "leading_shower"   },
    { name = "start_x",               type = "both_particle", selector = "leading_shower"   },
    { name = "start_y",               type = "both_particle", selector = "leading_shower"   },
    { name = "start_z",               type = "both_particle", selector = "leading_shower"   },
    { name = "pid",                   type = "both_particle", selector = "leading_shower"   }
]