[parameters]
photon_threshold = 25.0
electron_threshold = 70.0
muon_threshold = 25
pion_threshold = 25.0
proton_threshold = 25.0


[general]
output = "NuEES_variables"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

[[sample]]
name = "simulation"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input000-reweighted.flat.caf.root"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"
ismc = true

[[tree]]
name = "variables_nocuts"
sim_only = false
issignal = false
isdata = false
mode = "reco"
cut = []
branch = [
    {name = "neutrino_id",            type = "true"},
    {name = "cc",                    type = "mctruth"},
    {name = "pdg",                   type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "parent_pdg",            type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "interaction_type",      type = "mctruth"},
    {name = "interaction_mode",      type = "mctruth"},
    {name = "neutrino_energy",       type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "category",              type = "true"},
    {name = "visible_energy",        type = "both"},
    {name = "fiducial",              type = "reco"},
    {name = "containment",           type = "reco"},
    {name = "flash_time",            type = "reco"},
    {name = "flash_score",           type = "reco"},
#    {name = "beam_costheta",         type = "reco"},
    {name = "vertex_x",              type = "both"},
    {name = "vertex_y",              type = "both"},
    {name = "vertex_z",              type = "both"},
    {name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_threshold"   ]},
    {name = "ke",                    type = "both_particle", selector = "leading_electron"   },
    {name = "start_dedx",            type = "reco_particle", selector = "leading_electron"   },
    {name = "start_straightness",    type = "reco_particle", selector = "leading_electron"   },
    {name = "axial_spread",          type = "reco_particle", selector = "leading_electron"   },
    {name = "directional_spread",    type = "reco_particle", selector = "leading_electron"   },
    {name = "vertex_distance",       type = "reco_particle", selector = "leading_electron"   },
    {name = "electron_softmax",      type = "reco_particle", selector = "leading_electron"   },
    {name = "photon_softmax",        type = "reco_particle", selector = "leading_electron"   },
    {name = "e_theta2",              type = "both_particle", selector = "leading_electron"   },
]

[[tree]]
name = "variables_fidCut"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",     type = "reco" }
]
branch = [
    {name = "neutrino_id",            type = "true"},
    {name = "cc",                    type = "mctruth"},
    {name = "pdg",                   type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "parent_pdg",            type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "interaction_type",      type = "mctruth"},
    {name = "interaction_mode",      type = "mctruth"},
    {name = "neutrino_energy",       type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "category",              type = "true"},
    {name = "visible_energy",        type = "both"},
    {name = "fiducial",              type = "reco"},
    {name = "containment",           type = "reco"},
    {name = "flash_time",            type = "reco"},
    {name = "flash_score",           type = "reco"},
#    {name = "beam_costheta",         type = "reco"},
    {name = "vertex_x",              type = "both"},
    {name = "vertex_y",              type = "both"},
    {name = "vertex_z",              type = "both"},
    {name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_threshold"   ]},
    {name = "ke",                    type = "both_particle", selector = "leading_electron"   },
    {name = "start_dedx",            type = "reco_particle", selector = "leading_electron"   },
    {name = "start_straightness",    type = "reco_particle", selector = "leading_electron"   },
    {name = "axial_spread",          type = "reco_particle", selector = "leading_electron"   },
    {name = "directional_spread",    type = "reco_particle", selector = "leading_electron"   },
    {name = "vertex_distance",       type = "reco_particle", selector = "leading_electron"   },
    {name = "electron_softmax",      type = "reco_particle", selector = "leading_electron"   },
    {name = "photon_softmax",        type = "reco_particle", selector = "leading_electron"   },
    {name = "e_theta2",              type = "both_particle", selector = "leading_electron"   },
]

[[tree]]
name = "interactions"
sim_only = false
mode = "true"
cut = [
    {name = "neutrino", type = "true"},
    {name = "fiducial_cut", type = "true"},
    {name = "containment_cut", type = "true"},
]
branch = [
    {name = "iou", type = "both"},
    {name = "vertex_x", type = "both"},
    {name = "vertex_y", type = "both"},
    {name = "vertex_z", type = "both"},
    {name = "fiducial", type = "reco"},
    {name = "containment", type = "reco"},
    {name = "flash_time", type = "reco"},
    {name = "flash_total_pe", type = "reco"},
    {name = "flash_hypothesis", type = "reco"},
    {name = "visible_energy", type = "both"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "pdg", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "interaction_mode", type = "mctruth"},
]

[[tree]]
name = "events"
sim_only = false
mode = "event"
cut = [
    {name = "no_cut", type = "event"},
]
branch = [
    {name = "nnu", type = "event"},
    {name = "nintime", type = "event", parameters = [0.0, 1.6]},
]

[[category]] # 0 : Signal, fiducial neutrino events
cuts = [
    { name = "neutrino"        },
    { name = "fiducial_cut"    },
]

[[category]] # 4 : Neutral current events, fiducial and contained
cuts = [
    { name = "neutrino"        },
    { name = "!iscc"            },
]

[[category]] # 5 : Cosmic events
cuts = [
    { name = "!neutrino"        },
]

[[category]] # 6 : Other ?
cuts = [
]




