[samples]
[samples.mc]
key = "mc"
exposure_type = "pot"
override_exposure = 2.45e24
trees = ['selectedEvents',]

[samples.benchmark]
key = "mc"
exposure_type = "pot"
trees = ['selectedEvents',]
presel = 'opening_angle_reco > 0.8 and opening_angle_reco < 1.0'

[samples.benchmark_lowOA]
key = "mc"
exposure_type = "pot"
trees = ['selectedEvents',]
presel = 'opening_angle_reco > 0.0 and opening_angle_reco < 0.6'

[samples.truenu]
key = "mc"
exposure_type = "pot"
trees = ['selectedNu',]

[samples.mcnu]
key = "mcnu"
exposure_type = "pot"
#override_category = -10
#precompute = {'category=category+10'}
trees = ['selectedNu',]

[samples.pandora]
key = "mc"
exposure_type = "pot"
trees = ['selectedNu',]

[samples.mcsignal]
key = "mc"
exposure_type = "pot"
trees = ['signal_eff',]

[samples.offbeam]
key = "offbeam"
exposure_type = "pot"
trees = ['selectedNu',]

[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['selectedNu',]

[samples.intime]
key = "intime"
exposure_type = "livetime"
trees = ['selectedCos',]