
[[this_includes]]
file = '/nashome/m/micarrig/icarus/nuESpine/medulla/spineplot/configurations/common/styles.toml'


[[this_includes]]
file = '/nashome/m/micarrig/icarus/nuESpine/medulla/analysis/systematic_recipes.toml'

# Define your samples
[samples]
[samples.NuMIFull]
key = "NuMIFull"
exposure_type = "pot"
trees = ['true_signal']
# systematics = ['true_signal_multisimTree', 'true_signal_multisigmaTree', 'true_signal_NuMIFluxsimTree']
systematics = ['true_signal_NuMIfluxsimTree', 'true_signal_multisigmaTree']
branches = ["reco_fiducial_cut",
            "reco_flash_cut",
            "true_category",
            "true_neutrino_energy",
            "reco_ele_beam_open_angle",
            "reco_leading_electron_energy",
            "reco_containment_cut",
            "reco_has_particle_multiplicity",
            "reco_no_muons",
            "reco_vertex_distance_cut",
            "reco_track_length",
            "reco_electron_softmax_cut",
            "reco_primary_softmax_cut",
            "reco_leading_ele_energy_cut",
            "reco_reco_interaction_type",
            "true_hadronic_invariant_mass",
            "true_momentum_transfer",
            "true_interaction_mode",
            "true_ele_beam_open_angle",
            "true_leading_electron_energy"]

precompute = {"reco_category" = "np.where(true_category == 0, reco_reco_interaction_type, -1)", "reco_ele_beam_cosTheta" = "np.where(reco_ele_beam_open_angle != 10, np.cos(reco_ele_beam_open_angle), -10)", "true_ele_beam_cosTheta" = "np.where(true_ele_beam_open_angle != 10, np.cos(true_ele_beam_open_angle), -10)"}
# precompute = {"reco_category" = "np.where(true_category == 0, true_interaction_mode, -1)", "reco_ele_beam_cosTheta" = "np.where(reco_ele_beam_open_angle != 10, np.cos(reco_ele_beam_open_angle), -10)", "true_ele_beam_cosTheta" = "np.where(reco_ele_beam_open_angle != 10, np.cos(reco_ele_beam_open_angle), -10)"}

# [samples.NuMIFullNonSel]
# key = "NuMIFull"
# exposure_type = "pot"
# trees = ['true_signal_nonmatched']
# systematics = []
# branches = ["reco_fiducial_cut",
#             "reco_flash_cut",
#             "true_category",
#             "true_neutrino_energy",
#             "reco_leading_electron_ke",
#             "reco_ele_beam_open_angle",
#             "reco_leading_electron_energy",
#             "reco_containment_cut",
#             "reco_has_particle_multiplicity",
#             "reco_no_muons",
#             "reco_vertex_distance_cut",
#             "reco_track_length",
#             "reco_electron_softmax_cut",
#             "reco_primary_softmax_cut",
#             "reco_leading_ele_energy_cut",
#             "reco_reco_interaction_type",
#             "true_hadronic_invariant_mass",
#             "true_momentum_transfer",
#             "reco_flash_time",
#             "true_leading_electron_energy",
#             "true_ele_beam_open_angle"
#             ]
# precompute = {"reco_category" = "np.where(true_category == 0, reco_reco_interaction_type, -1)", "reco_ele_beam_cosTheta" = "np.where(reco_ele_beam_open_angle != 10, np.cos(reco_ele_beam_open_angle), -10)", "true_ele_beam_cosTheta" = "np.where(true_ele_beam_open_angle != 10, np.cos(true_ele_beam_open_angle), -10)"}
# # precompute = {"reco_category" = "np.where(true_category == 0, true_interaction_mode, -1)", "reco_ele_beam_cosTheta" = "np.where(reco_ele_beam_open_angle != 10, np.cos(reco_ele_beam_open_angle), -10)", "true_ele_beam_cosTheta" = "np.where(reco_ele_beam_open_angle != 10, np.cos(reco_ele_beam_open_angle), -10)"}


# Output directory for plots
[output]
path = 'plots/'

# Analysis configuration
[analysis]
ordinate_sample = 'NuMIFull'
category_branch = 'reco_category'

category_assignment = [
    [1], # QE-like
    [2], # MEC-like
    [3], # DIS-like
    [4], # RES-like
    [5, 0, -1]  # >1 electron, Other
]
category_labels = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)', 'Other']
category_colors = ['#2C194C','#49749F', '#83A1BE', '#8EB38D', '#4F894E', '#1C5B19', '#0F2903'] #cork

# category_assignment = [
#     [0], # QE
#     [1], # RES
#     [2], # DIS
#     [10], # MEC
#     [3, -1]  # COH, Other
# ]
# category_labels = ['QE', 'RES', 'DIS', 'MEC', 'Other']
# category_colors = ['#001261', '#1E6F9D', '#BE6533', '#8B2706', '#590008', '#000000ff']

category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram']

# Define your variables (if not already in included variables.toml)
[variables]
# [variables.true_neutrino_energy]
# key = 'true_neutrino_energy'  
# nbins = 20
# range = [0, 5]
# xlabel = 'True Neutrino Energy [GeV]'

# [variables.reco_ele_beam_cosTheta]
# key = 'reco_ele_beam_cosTheta'
# nbins = 13
# binning_scheme = 'custom_bins'
# custom_bins = [-1.0, -0.4, 0.0, 0.2, 0.35, 0.5, 0.625, 0.725, 0.8, 0.85, 0.9, 0.94, 0.97, 1.0]
# range = [-1.0, 1.0]
# xlabel = "Reco Leading Electron $cos{\theta_{NUMI}}$"

# [variables.reco_leading_electron_energy]
# key = 'reco_leading_electron_energy'
# nbins = 9
# range = [225.0, 5000.0]
# binning_scheme = 'custom_bins'
# custom_bins = [225, 350, 500, 650, 800, 1000, 1250, 1500, 2000, 5000]
# xlabel = 'Reco Leading Electron Energy [MeV]'

# [variables.true_hadronic_invariant_mass]
# key = 'true_hadronic_invariant_mass'
# nbins = 5
# range = [0.5, 2.0]
# xlabel = 'True Hadronic Invariant Mass (W) [GeV]'

# [variables.true_momentum_transfer]
# key = 'true_momentum_transfer'
# nbins = 12
# range = [0.0, 2.4]
# xlabel = 'True Momentum Transfer ($Q^{2}$) [GeV$^{2}$]'

[variables.true_leading_electron_energy]
key = 'true_leading_electron_energy'
nbins = 9
range = [225.0, 5000.0]
binning_scheme = 'custom_bins'
custom_bins = [225, 350, 500, 650, 800, 1000, 1250, 1500, 2000, 5000]
xlabel = 'True Leading Electron Energy [MeV]'

# [variables.true_ele_beam_cosTheta]
# key = 'true_ele_beam_cosTheta'
# nbins = 13
# binning_scheme = 'custom_bins'
# custom_bins = [-1.0, -0.4, 0.0, 0.2, 0.35, 0.5, 0.625, 0.725, 0.8, 0.85, 0.9, 0.94, 0.97, 1.0]
# range = [-1.0, 1.0]
# xlabel = "True Leading Electron $cos{\theta_{NUMI}}$"

# Create efficiency plot figures
# [[figure]]
# name = 'selection_efficiency_table'
# type = 'SimpleFigure'
# style = 'basic_icarus'  # This references a style defined in the included styles.toml
# title = 'Signal Selection Efficiency'

# [[figure.artists]]
# type = 'SpineEfficiency'
# variable = 'true_neutrino_energy'
# groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)', '$\geq1e$ (Other-e)', 'Other']
# # groups = ['QE', 'RES', 'DIS', 'MEC', 'Other']

# [figure.artists.cuts]
# reco_fiducial_cut = 'Fiducial Volume'
# reco_flash_cut = 'Flash Cut'
# reco_containment_cut = 'Interaction Containment Cut'
# reco_has_particle_multiplicity = '>=1 Electron-like Particle'
# reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
# reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
# reco_no_muons = 'No Muon-like Particles'
# reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'
# reco_leading_ele_energy_cut = 'Leading Electron Energy > 225 MeV'

# [figure.artists.draw_kwargs]
# show_option = 'table'
# percentage = true
# show_seqeff = true
# show_unseqeff = true
# show_purity = true
# show_counts = true

# # FIGURE 2: Efficiency vs Neutrino Energy Plot 
# [[figure]]
# name = 'efficiency_vs_energy'
# type = 'SimpleFigure'
# style = 'basic_icarus'
# title = 'Selection Efficiency vs True Neutrino Energy'

# [[figure.artists]]
# type = 'SpineEfficiency'
# variable = 'true_neutrino_energy'
# groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)']
# # groups = ['QE', 'RES', 'DIS', 'MEC']

# xrange = [0, 5]
# xtitle = 'True Neutrino Energy [GeV]'

# [figure.artists.cuts]
# reco_fiducial_cut = 'Fiducial Volume'
# reco_flash_cut = 'Flash Cut'
# reco_containment_cut = 'Interaction Containment Cut'
# reco_has_particle_multiplicity = '>=1 Electron-like Particle'
# reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
# reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
# reco_no_muons = 'No Muon-like Particles'
# reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'

# [figure.artists.draw_kwargs]
# show_option = 'final_only' 
# percentage = true
# show_seqeff = true     # Show cumulative efficiency curve
# show_unseqeff = false  # Don't show individual cut curves

# # FIGURE 3: Efficiency vs Electron Energy Plot 
# [[figure]]
# name = 'efficiency_vs_electronEnergy'
# type = 'SimpleFigure'
# style = 'basic_icarus'
# title = 'Selection Efficiency vs Reco Electron Energy'

# [[figure.artists]]
# type = 'SpineEfficiency'
# variable = 'reco_leading_electron_energy'
# groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)']
# # groups = ['QE', 'RES', 'DIS', 'MEC']
# xrange = [0, 5000]
# xtitle = 'Reco Electron Energy [MeV]'

# [figure.artists.cuts]
# reco_fiducial_cut = 'Fiducial Volume'
# reco_flash_cut = 'Flash Cut'
# reco_containment_cut = 'Interaction Containment Cut'
# reco_has_particle_multiplicity = '>=1 Electron-like Particle'
# reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
# reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
# reco_no_muons = 'No Muon-like Particles'
# reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'
# reco_leading_ele_energy_cut = 'Leading Electron Energy > 225 MeV'

# [figure.artists.draw_kwargs]
# show_option = 'final_only'  # KEY: This makes it a plot vs energy!
# percentage = true
# show_seqeff = true     # Show cumulative efficiency curve
# show_unseqeff = false  # Don't show individual cut curves

# # FIGURE 4: Efficiency vs Electron Polar Angle Plot 
# [[figure]]
# name = 'efficiency_vs_electronAngle'
# type = 'SimpleFigure'
# style = 'basic_icarus'
# title = 'Selection Efficiency vs Reco Electron $cos{\theta_{NUMI}}$'

# [[figure.artists]]
# type = 'SpineEfficiency'
# variable = 'reco_ele_beam_cosTheta'
# groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)']
# # groups = ['QE', 'RES', 'DIS', 'MEC']
# xtitle = 'Reco Electron $cos{\theta_{NUMI}}$'

# [figure.artists.cuts]
# reco_fiducial_cut = 'Fiducial Volume'
# reco_flash_cut = 'Flash Cut'
# reco_containment_cut = 'Interaction Containment Cut'
# reco_has_particle_multiplicity = '>=1 Electron-like Particle'
# reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
# reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
# reco_no_muons = 'No Muon-like Particles'
# reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'
# reco_leading_ele_energy_cut = 'Leading Electron Energy > 225 MeV'

# [figure.artists.draw_kwargs]
# show_option = 'final_only'  # KEY: This makes it a plot vs energy!
# percentage = true
# show_seqeff = true     # Show cumulative efficiency curve
# show_unseqeff = false  # Don't show individual cut curves

# # FIGURE 5: Efficiency vs True Invariant Mass Plot
# [[figure]]
# name = 'efficiency_vs_trueInvariantMass'
# type = 'SimpleFigure'
# style = 'basic_icarus'
# title = 'Selection Efficiency vs True Hadronic Invariant Mass (W)'

# [[figure.artists]]
# type = 'SpineEfficiency'
# variable = 'true_hadronic_invariant_mass'
# # groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)']
# groups = ['QE', 'RES', 'DIS', 'MEC']
# xtitle = 'True Hadronic Invariant Mass (W) [GeV]'

# [figure.artists.cuts]
# reco_fiducial_cut = 'Fiducial Volume'
# reco_flash_cut = 'Flash Cut'
# reco_containment_cut = 'Interaction Containment Cut'
# reco_has_particle_multiplicity = '>=1 Electron-like Particle'
# reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
# reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
# reco_no_muons = 'No Muon-like Particles'
# reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'
# reco_leading_ele_energy_cut = 'Leading Electron Energy > 225 MeV'

# [figure.artists.draw_kwargs]
# show_option = 'final_only'  # KEY: This makes it a plot vs energy!
# percentage = true
# show_seqeff = true     # Show cumulative efficiency curve
# show_unseqeff = false  # Don't show individual cut curves

# # FIGURE 6: Efficiency vs True Momentum Transfer Plot 
# [[figure]]
# name = 'efficiency_vs_trueMomentumTransfer'
# type = 'SimpleFigure'
# style = 'basic_icarus'
# title = 'Selection Efficiency vs True Momentum Transfer (Q^2) [GeV$^{2}$]'

# [[figure.artists]]
# type = 'SpineEfficiency'
# variable = 'true_momentum_transfer'
# groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)']
# # groups = ['QE', 'RES', 'DIS', 'MEC']
# xtitle = 'True Momentum Transfer ($Q^{2}$) [GeV$^{2}$]'

# [figure.artists.cuts]
# reco_fiducial_cut = 'Fiducial Volume'
# reco_flash_cut = 'Flash Cut'
# reco_containment_cut = 'Interaction Containment Cut'
# reco_has_particle_multiplicity = '>=1 Electron-like Particle'
# reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
# reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
# reco_no_muons = 'No Muon-like Particles'
# reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'
# reco_leading_ele_energy_cut = 'Leading Electron Energy > 225 MeV'

# [figure.artists.draw_kwargs]
# show_option = 'final_only'  # KEY: This makes it a plot vs energy!
# percentage = true
# show_seqeff = true     # Show cumulative efficiency curve
# show_unseqeff = false  # Don't show individual cut curves

# FIGURE 8: Efficiency vs true leading electron energy
[[figure]]
name = 'efficiency_vs_trueLeadingElectronEnergy'
type = 'SimpleFigure'
style = 'basic_icarus'
title = 'Selection Efficiency vs True Leading Electron Energy [MeV]'

[[figure.artists]]
type = 'SpineEfficiency'
variable = 'true_leading_electron_energy'
groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)', 'Other']
# groups = ['QE', 'RES', 'DIS', 'MEC']
xtitle = 'True Leading Electron Energy [MeV]'

[figure.artists.cuts]
reco_fiducial_cut = 'Fiducial Volume'
reco_flash_cut = 'Flash Cut'
reco_containment_cut = 'Interaction Containment Cut'
reco_has_particle_multiplicity = '>=1 Electron-like Particle'
reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
reco_no_muons = 'No Muon-like Particles'
reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'
reco_leading_ele_energy_cut = 'Leading Electron Energy > 225 MeV'

[figure.artists.draw_kwargs]
show_option = 'final_only'  # KEY: This makes it a plot vs energy!
percentage = true
show_seqeff = true     # Show cumulative efficiency curve
show_unseqeff = false  # Don't show individual cut curves
draw_error = 'total'

# FIGURE 9: Efficiency vs true leading electron cosTheta Numi
# [[figure]]
# name = 'efficiency_vs_trueLeadingElectronCosTheta'
# type = 'SimpleFigure'
# style = 'basic_icarus'
# title = 'Selection Efficiency vs True Leading Electron $cos{\theta_{NUMI}}$'

# [[figure.artists]]
# type = 'SpineEfficiency'
# variable = 'true_ele_beam_cosTheta'
# groups = ['1e1p0$\pi$ (QE-like)', '1e2p0$\pi$ (MEC-like)', '1e$\geq3p0\pi$ (DIS-like)', '1e1$\pi$ (RES-like)', 'Other']
# # groups = ['QE', 'RES', 'DIS', 'MEC']
# xtitle = 'True Leading Electron $cos{\theta_{NUMI}}$'

# [figure.artists.cuts]
# reco_fiducial_cut = 'Fiducial Volume'
# reco_flash_cut = 'Flash Cut'
# reco_containment_cut = 'Interaction Containment Cut'
# reco_has_particle_multiplicity = '>=1 Electron-like Particle'
# reco_electron_softmax_cut = 'Leading Electron Electron-Softmax > 0.72'
# reco_primary_softmax_cut = 'Leading Electron Primary-Softmax > 0.97'
# reco_no_muons = 'No Muon-like Particles'
# reco_vertex_distance_cut = 'Vertex Distance < 3.25 cm'
# reco_leading_ele_energy_cut = 'Leading Electron Energy > 225 MeV'

# [figure.artists.draw_kwargs]
# show_option = 'final_only'  # KEY: This makes it a plot vs energy!
# percentage = true
# show_seqeff = true     # Show cumulative efficiency curve
# show_unseqeff = false  # Don't show individual cut curves